# Generated by Django 3.1.7 on 2021-04-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.TextField()),
                ('x2', models.TextField()),
                ('x3', models.TextField()),
                ('x4', models.TextField()),
                ('x5', models.TextField()),
                ('x6', models.TextField()),
                ('x8', models.TextField()),
                ('x9', models.TextField()),
            ],
            options={
                'db_table': 'csv_data',
            },
        ),
    ]
